using FarmControl.Base.BaseRepository.BaseQueryGenericRepository;
using FarmControl.Features.Entities;
namespace FarmControl.Features.Repositories.QueryRepository.FarmerQueryRepository;

public interface IFarmerQueryRepository:IQueryGenericRepository<Farmer>;