using FarmControl.Base.BaseRepository.BaseQueryGenericRepository;
using FarmControl.Features.Entities;
namespace FarmControl.Features.Repositories.QueryRepository.FieldQueryRepository;

public interface IFieldQueryRepository:IQueryGenericRepository<Field>;