using FarmControl.Base.BaseRepository.BaseQueryGenericRepository;
using FarmControl.Features.Entities;
namespace FarmControl.Features.Repositories.QueryRepository.ProductQueryRepository;

public interface IProductQueryRepository:IQueryGenericRepository<Product>;